### ISSUE TITLE
fix(profile-page): build fails — missing i18next in node_modules

### ISSUE THREAD

**Issue by atimics** [cenetex/swarm#1183]
## Objective
Ensure `pnpm build` completes successfully by resolving missing dependencies and build errors.

## Problem
`pnpm build` fails because:
1. `i18next` dependency is not installed despite being declared in `packages/profile-page/package.json` 
2. TypeScript compilation error in admin-api prevents build completion

## Root cause
- The lockfile was updated when `i18next` was added, but `pnpm install` was not run
- TypeScript type narrowing issue introduced in #1180 causes compilation failure

## Scope
- Run `pnpm install` to install missing dependencies
- Fix TypeScript error in admin-api pause tool loop detection
- Verify `pnpm build` completes successfully

## Constraints
- Minimal changes only - fix TypeScript error without refactoring
- Keep fix focused on build completion

## Acceptance criteria
- [ ] `pnpm install` resolves all missing dependencies
- [ ] `pnpm build` completes successfully (tsc + admin-ui + profile-page)

## Package
`profile-page`, `admin-api`

**Comment by atimics** [comment]
## Agent re-run needed

PR #1185 has the build fix but CI is still failing:
- **Lint: FAILED**
- **Test: FAILED**

Build and smoke test pass. Please fix the lint and test failures on branch `fix/issue-1183-typescript-error` and push a follow-up commit.
